# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['gracious_tu:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
 - "alert_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'python-metrics'
    static_configs:
        - targets: [ 'host.docker.internal:8080' ]



          s3://qaecm-network-visibility-dms-pg-to-redshift-qa4/hacker_h_bhai_hacker_h/date_hour=2025-02-05 00:00:00/network_id=01H4SEHY8B1M54PRX4RB0DBEEY/0000_part_00.parquet
          
          explain select flow_id from read_parquet('s3://qaecm-network-visibility-dms-pg-to-redshift-qa4/hacker_h_bhai_hacker_h/**') where date_hour between '2025-02-05 00:05' and '2025-02-05 00:10';
          
          
          select created_at, date_hour from read_parquet('s3://qaecm-network-visibility-dms-pg-to-redshift-qa4/hacker_h_bhai_hacker_h/date_hour=2025-02-05 00:00:00/network_id=01H4SEHY8B1M54PRX4RB0DBEEY/*.parquet');
          
          explain select created_At from read_parquet('s3://qaecm-network-visibility-dms-pg-to-redshift-qa4/hacker_h_bhai_hacker_h/**') where date_hour between '2025-02-05 00:05' and '2025-02-05 12:10' and created_at between '2025-02-05 05:0:22' and '2025-02-05 07:0:22';

        explain select created_At, network_id from read_parquet('s3://qaecm-network-visibility-dms-pg-to-redshift-qa4/hacker_h_bhai_hacker_h/**') where date_hour between '2025-02-05 05:0:22' and '2025-02-07 07:0:22' and created_at between '2025-02-05 05:0:22' and '2025-02-07 07:0:22';